binomial dist. diagramm added, minor improvements and clarifications
latex4ei/Stochastische-Signale pull request #2
Opened 2018-02-10 13:28 UTC by Alwinius

Bitte mergen, wenn ihr mit den Änderungen einverstanden seid und neue Version auf Website veröffentlichen (die aktuellste enthält commits der letzten zwei Jahren noch nicht).

2018-02-10 17:27 UTC, hofbi commented
Ich schaus mir mal durch und aktualisiere die website

2018-02-11 18:15 UTC, hofbi requested changes
* Kannst du das `.directory` file noch entfernen

2018-02-11 18:28 UTC, hofbi approved these changes

2018-02-11 18:28 UTC, merged

2018-02-11 20:13 UTC, hofbi commented
@Alwinius Neuste Änderungen sind online

2018-02-12 07:05 UTC, Alwinius commented
super danke