rework for ws19/20
latex4ei/Stochastische-Signale pull request #6
Opened 2020-01-22 20:14 UTC by veecue

[diff pdf for your convenience](https://github.com/latex4ei/Stochastische-Signale/files/4099733/StochastischeSignale.pdf)

2020-02-10 00:04 UTC, thielpa requested changes

2020-02-10 00:04 UTC, HappyDayHunter commented on StochastischeSignale.tex
> +	$\Rightarrow \hat{\Y} = \rho_{\X,\Y}\dfrac{\sigma_{\Y}}{\sigma_{\X}}(\X-E[\X])+E[\Y]$
Add line break after this line

2020-02-10 00:04 UTC, HappyDayHunter commented on StochastischeSignale.tex
> +	\item $P(\{|\X_n|\leq\Y\}) = 1 \forall n \wedge E[Y^2]<\infty\wedge \X_n\xrightarrow{\text{p.}}\X \Rightarrow \X_n\xrightarrow{\text{m.s.}}\X$
Add line break before right arrow

2025-03-07 09:05 UTC, stevensalloum approved these changes

2025-03-07 09:14 UTC, merged